### ISSUE TITLE
Change wallet address.

### ISSUE THREAD

**Issue by sv9988** [sponnet/faucetserver#1]
I try to change wallet address to my ETH wallet at sendTransaction function and test on TestNet. 
But when build and send ETH to another, it will be error.
So, please tell me how to change wallet address in your sample. Thank you!

**Comment by sponnet** [comment]
can you specify what the error is and what exactly did you change in the code ?

**Comment by sponnet** [comment]
Oh and please refer to this repo : https://github.com/sponnet/locals-faucetserver you're working on an ancient version of the faucet.

**Comment by sv9988** [comment]
I change my wallet at sendTransacsion function.
So, what should i do if i want to use my wallet, not existed wallet in wallet.js

Thanks,
